### ISSUE TITLE
Object.assign on purpose?

### ISSUE THREAD

**Issue by ssupinsky** [uiwjs/uiw#103]
Is Object.assign preferred in your codebase over the spread operator?
I'm looking at https://github.com/uiwjs/uiw/blob/481104fcd439b601d00bd9aea5cb104b9b07052d/packages/react-radio/src/RadioGroup.tsx#L22

I can create a pull request if it's not intended

**Comment by jaywcjlove** [comment]
@ssupinsky Welcome to create PR.
