### ISSUE TITLE
Add @types/uiw, not works on typescript project.

### ISSUE THREAD

**Issue by ghost** [uiwjs/uiw#148]
For example: Popover
Error:
(alias) class Popover
import Popover
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
'Popover' cannot be used as a JSX component.
  Its instance type 'Popover' is not a valid JSX element.
    Type 'Popover' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2786)

**Comment by jaywcjlove** [comment]
@luisthread Are there any examples?

**Comment by jaywcjlove** [comment]
@luisthread https://github.com/uiwjs/uiw-example-create-react-app/tree/issue-148

**Comment by jaywcjlove** [comment]
problem solved [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/uiw@4.8.3/file/README.md)

@ghost
