### ISSUE TITLE
overylay hooks问题

### ISSUE THREAD

**Issue by Nickynodejs** [uiwjs/uiw#156]
把overlay改成hooks时推出弹窗没有动画显示

**Comment by jaywcjlove** [comment]
@Nickynodejs 是否有可运行实例？

**Comment by Nickynodejs** [comment]
不好意思最近有点忙，您把react-overlay改成hooks组件推出效果就没了，我试过了不知道问题在哪里，想向您请教下。

**Comment by jaywcjlove** [comment]
@Nickynodejs 有没有可运行的实例呢？我看看

**Comment by Nickynodejs** [comment]
这个是预览地址，https://codesandbox.io/s/infallible-goldberg-gv615

**Comment by jaywcjlove** [comment]
@Nickynodejs 我换成了引入 uiw  包 `import Overlay from "@uiw/react-overlay";` 就没有问题了，其它我什么代码都没有改过你试一试下面实例。

```jsx
import Overlay from "@uiw/react-overlay";
```

https://codesandbox.io/s/react-overlay-156-5xbpd-5xbpd

**Comment by Nickynodejs** [comment]
我是想问，您的 react-overlay组件改成hooks组件会不会也出现退出动画消失的问题。

**Comment by jaywcjlove** [comment]
@Nickynodejs 😆 这个就是实现方式的问题了，肯定不会，当初我用 class 封装组件的时候有你的实例的表现，

里面已经有很多已经换成了 hook 组件，这个应该会在某个空闲的事件段换成 hook ，毕竟性能会提高一点点，代码体积会小一点点。

**Comment by jaywcjlove** [comment]
@Nickynodejs 欢迎解决并提交 PR

**Comment by Nickynodejs** [comment]
非常感谢
