### ISSUE TITLE
Descriptions 使用占位样式问题

### ISSUE THREAD

**Issue by wei1553** [uiwjs/uiw#223]
![image](https://user-images.githubusercontent.com/34849519/106867785-fa335700-6708-11eb-8621-610ffba69fe9.png)

### 问题描述：
当Descriptions.Item 在列头部设置span为2时，样式的展示和占位并不正确。

**Comment by jaywcjlove** [comment]
@wei1553 https://codepen.io/jaywcjlove/pen/dyOYrrb

**Comment by jaywcjlove** [comment]
@wei1553  https://codesandbox.io/embed/uiw-demo-pjjb9

测试了一下没有问题的样子

**Comment by wei1553** [comment]
> @ wei1553 https://codesandbox.io/embed/uiw-demo-pjjb9
> 
> 测试了一下没有问题的样子

把更新时间的2放到创建时间，会出现问题的。

**Comment by jaywcjlove** [comment]
@wei1553 没有明白什么意思

**Comment by wei1553** [comment]
> @wei1553 没有明白

> @wei1553 没有明白什么意思

<Descriptions.Item label="创建时间" span={2}>2018-04-24 18:00:00</Descriptions.Item>
    <Descriptions.Item label="更新时间">
      2019-04-24 18:00:00
    </Descriptions.Item>
    
    
    - span={2} 放到列前面这个元素

**Comment by jaywcjlove** [comment]
@wei1553 thx! Upgrade `v4.7.11`
