### ISSUE TITLE
配合react-heat-map显示时有bug

### ISSUE THREAD

**Issue by Vang-z** [uiwjs/uiw#422]
![Snipaste_2021-08-06_10-39-13](https://user-images.githubusercontent.com/44422499/128447922-60f14bbf-8107-4a67-a195-534c36d5c283.png)
鼠标快速滑动时出现对话框不会消失

 "react": "^17.0.2",
 "react-dom": "^17.0.2",
 "@uiw/react-heat-map": "^1.3.3",
 "@uiw/react-tooltip": "^4.9.4",

**Comment by jaywcjlove** [comment]
@Vang-z 你可以先试用  `"@uiw/react-tooltip": "4.7.16"` 解决问题。

**Comment by Vang-z** [comment]
> @Vang-z 你可以先试用 `"@uiw/react-tooltip": "4.7.16"` 解决问题。

谢谢及时回复，同样无法正确隐藏提示框
![Snipaste_2021-08-06_10-55-03](https://user-images.githubusercontent.com/44422499/128449251-40dec962-43f3-49f0-ae91-8f32a0a8df45.png)
![Snipaste_2021-08-06_10-55-18](https://user-images.githubusercontent.com/44422499/128449256-8a97d5c6-97c1-44bd-9632-2d9e63da3483.png)

切换使用material-ui/tooltip 暂时解决问题，等待版本更新
![Snipaste_2021-08-06_10-58-47](https://user-images.githubusercontent.com/44422499/128449413-af414481-2eda-4a81-a18b-6f3d80c05015.png)

最后还有个问题 请问如何修改点击热力图时日期方块为绿色的样式 有直接的api吗

**Comment by jaywcjlove** [comment]
@Vang-z https://uiwjs.github.io/react-heat-map/ 刚测试了官方实例 没有问题。

react-heat-map 组件问题在对应仓库提问，可以使用 `rectRender` 实现。

**Comment by Vang-z** [comment]
好的 谢谢
