### ISSUE TITLE
运行示列代码出错

### ISSUE THREAD

**Issue by nanzm** [uiwjs/uiw#435]
克隆代码后 运行  npm run start ， 打开页面， 浏览器报错

![image](https://user-images.githubusercontent.com/12454813/131065204-08f65565-a878-495d-911d-963dbc2eae14.png)

**Comment by jaywcjlove** [comment]
克隆下来运行文档网站，需要下面三步：

1. 安装依赖

```bash
$ npm install 
```

2. 安装子包和文档网站依赖

```bash
$ npm run hoist 
```

3. 编译包

```bash
$ npm run build 
```

完成上面 3步，再运行文档示例网站。
