### ISSUE TITLE
关于时间的组件显示异常

### ISSUE THREAD

**Issue by hahaha27** [uiwjs/uiw#447]
![图片](https://user-images.githubusercontent.com/90236440/132288925-95465680-9b91-4ba9-8557-a3a0e470eccb.png)

**Comment by hahaha27** [comment]
![图片](https://user-images.githubusercontent.com/90236440/132289394-80eb7cd5-2210-4c86-8d30-7284ed0ee745.png)

**Comment by jaywcjlove** [comment]
@hahaha27 关了是没有问题？

**Comment by hahaha27** [comment]
只有在gitee上面有错误，在github上面是没错的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uiwjs/uiw"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uiwjs/uiw] 关于时间的组件显示异常 (#447)





 
@hahaha27 关了是没有问题？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
