### ISSUE TITLE
Bugs: 写ts的时候，使用Empty组件ts提示错误

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw#549]
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/24369183/155051863-56826c9f-6427-4863-9551-38039af210c9.png">

使用以上的demo，ts提示缺少属性 "iconProps"

https://github.com/uiwjs/uiw/blob/64c76c7bf734ae53aef6fe9b90ed360dc7e31863/packages/react-empty/src/index.tsx#L8

`iconProps` 设置了必填

**Comment by jaywcjlove** [comment]
@xingyuefeng 以修复等待发版
