### ISSUE TITLE
样式问题：时间选择器会出现横向滚动条，希望去除

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw#552]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/24369183/155472566-302e9184-0e61-48a0-b806-d729d986113c.png">

**Comment by nullptr-z** [comment]
@xingyuefeng 已在https://github.com/uiwjs/uiw/pull/571提交中修复

**Comment by nullptr-z** [comment]
> https://github.com/uiwjs/uiw/pull/571 提交中修复

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/uiw/pull/571
