### ISSUE TITLE
文档理解困惑

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#553]
![image](https://user-images.githubusercontent.com/87160683/155473778-2a93daff-e8b4-4ff6-ada8-e5adb02ae692.png)

List 组件文档文字错误 https://uiwjs.github.io/#/components/list

**Comment by nullptr-z** [comment]
@gssggssg  感谢反馈,已修正!  如果感兴趣可以Fork项目,修正后发起Pull Request
