### ISSUE TITLE
SearchSelect 搜索选择器运行不报错，build时报少必要参数tagProps

### ISSUE THREAD

**Issue by Amber-Nan** [uiwjs/uiw#574]
![1681646104035_ pic](https://user-images.githubusercontent.com/66067296/156097555-d1da81d5-2f3a-4ba9-b65c-04b45514bfdc.jpg)

**Comment by jaywcjlove** [comment]
@Amber-Nan 可以先忽略，下一个版本发布

```jsx
<SearchSelect
  // @ts-ignore
  tagProps={....}
```

**Comment by Amber-Nan** [comment]
@jaywcjlove  好的

**Comment by Amber-Nan** [comment]
已解决
