### ISSUE TITLE
Tree组件 openKeys参数失效

### ISSUE THREAD

**Issue by dibenny** [uiwjs/uiw#582]
问题如图，使用 openKeys参数 选中 崇文区底下的东花市街道key值  无效
![image](https://user-images.githubusercontent.com/44771226/156280684-ffdf2043-0745-40d3-b21d-859b129a12b1.png)

期待：选中节点展开

**Comment by nullptr-z** [comment]
@dibenny 已修复
* https://github.com/uiwjs/uiw/pull/588

**Comment by dibenny** [comment]
已测试  已修复
