### ISSUE TITLE
Bug: SearchTree组件使用问题

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw#584]
1. 没有数据的情况，应提示暂无数据之类的描述...
<img width="369" alt="image" src="https://user-images.githubusercontent.com/24369183/156287161-23934d98-b6be-4cd5-8873-8478539e9c39.png">

2. 点击清除会再次弹出选择框

<img width="470" alt="image" src="https://user-images.githubusercontent.com/24369183/156287281-4aedafc7-2b9e-4deb-80ce-b543e9a7b58f.png">

3. Form中使用demo验证设置的必填，没有提示错误

**Comment by nullptr-z** [comment]
@xingyuefeng 已修复
* https://github.com/uiwjs/uiw/pull/586
