### ISSUE TITLE
SearchTree报错：单选框提示key为undefined！！！

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#591]
当单选框中没内容时，点击单选框，将会提示报错，并卸载组件

版本信息
. uiw:[4.13.3](https://uiwjs.github.io/#/)[](https://uiwjs.github.io/#/guide)

## 错误信息：
错误组件
![image](https://user-images.githubusercontent.com/87160683/156339314-f412eb63-ce71-44b0-ba23-226b7bb8fe2d.png)
报错截图：
![image](https://user-images.githubusercontent.com/87160683/156339704-79252476-fe01-492b-a5a8-0ae99ebbddfc.png)

## 重现步骤：
1. 清除单选框内容
2. 点击单选框
3. 提示报错，卸载组件

**Comment by nullptr-z** [comment]
@gssggssg 在[uiw v4.13.4](https://github.com/uiwjs/uiw/releases/tag/v4.13.4)中修复
