### ISSUE TITLE
SearchTree :展示下拉展开问题

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#597]
### 描述
搜索上海，展示的 Tree 多选组件，不能正确展开

### 环境：
uiw：[4.13.4](https://uiwjs.github.io/#/)
浏览器：98.0.4758.102（正式版本） （64 位）
系统：windows

### 步骤：
1. 搜索上海市
2. 下拉框出现上海市，但是未出现上海市下属
3. 点击上海市，全选中上海市及其下属

![image](https://user-images.githubusercontent.com/87160683/156489514-a8c3a993-0f35-4739-bcdf-58ee817d0530.png)

**Comment by nullptr-z** [comment]
@gssggssg 应该是用一个问题 #594 已经修复
* https://github.com/uiwjs/uiw/issues/594
