### ISSUE TITLE
DatePicker 日期选择器可以返回YYYY-MM-DD格式

### ISSUE THREAD

**Issue by wangwei88** [uiwjs/uiw#602]
![image](https://user-images.githubusercontent.com/21116000/156523703-fd598e2a-66d4-4303-99ab-390fd5532e08.png)

**Comment by jaywcjlove** [comment]
https://uiwjs.github.io/#/components/formatter

@wangwei88 提供了 formatter 方法，这个方法是内置的方法。

https://github.com/uiwjs/uiw/blob/d64436639a08b27a0c85126db29f3cd8a1d4fb93/packages/uiw/src/index.ts#L81

```js
console.log(formatter('YYYY年MM月DD日', new Date(2019, 3, 7)))
//=> 2019年04月07日
console.log(formatter('YYYY年MM月DD日 16:30:29', new Date(2019, 3, 7, 16, 30, 29)))
//=> 2019年04月07日 16:30:29
```

目前没有必要提供格式化功能，引发其它组件错误
