### ISSUE TITLE
[SearchTree]: 单选的时候，取消选中列表，样式上像取消了,值还在

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw#619]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/24369183/156977568-f3c76d7f-ac0f-4b77-b459-66f29e649bef.png">

https://uiwjs.github.io/#/components/search-tree 基础实例demo

已经取消上海市，但值还在

**Comment by nullptr-z** [comment]
@xingyuefeng 已修复

**Comment by xingyuefeng** [comment]
@nullptr-z key为0 children内容不显示
