### ISSUE TITLE
[Progress <进度条>]: 数值太小样式显示错误

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#623]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

数值太小样式显示错误

### 错误复现

重现行为的步骤：

1. 将`Progress`组件的`percent`属性值设置为小于2

### 重现示例

```
import ReactDOM from 'react-dom';
import { Progress } from 'uiw';

const Demo = () => (
  <div>
    <Progress.Line strokeWidth={18} percent={1} status="exception" />
  </div>
);
ReactDOM.render(<Demo />, _mount_);
```

### 预期行为

进度颜色填充在进度条组件圆角内部

### 截图

![c1914f4cf6a79bf7fbe0b98c2379be7](https://user-images.githubusercontent.com/87160683/156995599-f808f436-f96a-4f09-8b9e-39e2a3e617c8.png)

![image](https://user-images.githubusercontent.com/87160683/156996120-3747e877-a26d-42df-8877-62bb33b58e12.png)

### 桌面（请填写以下信息）：

- UIW：[4.13.6](https://uiwjs.github.io/#/)
- 操作系统：win10
- 浏览器：Chrome
- 版本和构建： 98.0.4758.102

**Comment by nullptr-z** [comment]
@gssggssg 已修复
