### ISSUE TITLE
SearchTree： 卡顿

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw#629]
在使用[demo Form中使用](https://uiwjs.github.io/#/components/search-tree) 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/24369183/157171403-b3a296fc-5c5d-4f1f-b8dc-9c399e912c4d.png">

搜索的时候明显感觉到数据展示卡顿，期望优化下

**Comment by nullptr-z** [comment]
@xingyuefeng 防抖延迟600ms,是否需要提供api手动设置

**Comment by xingyuefeng** [comment]
@nullptr-z 个人觉得不应该组件加防抖。 防抖用途主要是搜索时异步加载数据，防止频繁加载时候用。用户通过`onSearch` 自己写防抖加载数据就行。
