### ISSUE TITLE
Form组件中使用FileInput上传图片出现数据格式问题

### ISSUE THREAD

**Issue by dibenny** [uiwjs/uiw#642]
问题如下：
在form表单中使用fileinput组件 提交表单数据时，图片数据处理错误
![image](https://user-images.githubusercontent.com/44771226/157391667-95959038-851e-4c46-a8e9-4695b4b8650f.png)

fileinput组件在form中的使用代码片段
<img width="767" alt="image" src="https://user-images.githubusercontent.com/44771226/157391880-9965ab81-a19a-4e19-8b47-4769cb21f2ca.png">

期望结果
提交正确的图片表单数据

**Comment by nullptr-z** [comment]
@dibenny 删除外层div, 在children回调内控制布局
![image](https://user-images.githubusercontent.com/48251883/157577767-aa3a1538-3a07-4e8b-91f5-34d8ddedf86e.png)
