### ISSUE TITLE
期望uiw也加一个穿梭框的组件

### ISSUE THREAD

**Issue by hy916** [uiwjs/uiw#658]
业务需求，期望添加一个穿梭框组件

<img width="683" alt="image" src="https://user-images.githubusercontent.com/32630937/158091717-a25c2fb1-88e2-4102-bb63-3772e6d798e1.png">

**Comment by nullptr-z** [comment]
@hy916 在 [v4.14.0+](https://www.npmjs.com/package/@uiw/react-transfer) 中已添加
