### ISSUE TITLE
期望选择完时间 直接关闭弹窗

### ISSUE THREAD

**Issue by matuancc** [uiwjs/uiw#660]
**描述您想要的解决方案**

在from表单中，选择完时间不会自动关闭，单独使用 选择完时间 可以直接关闭弹窗

**附加上下文**

![image](https://user-images.githubusercontent.com/33281802/158112975-da67230a-fb25-4dd2-8be1-b358541de9fc.png)

**Comment by nullptr-z** [comment]
@matuancc @Amber-Nan  v4.15.1中增加 autoClose参数,设置为true可以自动关闭
