### ISSUE TITLE
标签页 <Tabs >: 高亮下划线位置错误

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#674]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

当tavs高度变化时，当前选中 tabs 高亮横线位置会发生改变

### 错误复现

重现行为的步骤：

1. 转到 行样式
2. 点击 code
3. 位置发生变化

### 预期行为

横线位置能正确

### 截图

![image](https://user-images.githubusercontent.com/87160683/158515067-367b354c-f55d-4a57-9877-28c2a4dd58d8.png)

### 桌面（请填写以下信息）：

- UIW：[4.14.0](https://uiwjs.github.io/#/)
- 操作系统：windows10
- 浏览器：Chrome
- 版本和构建：9.0.4844.51（正式版本） （64 位）

**Comment by Amber-Nan** [comment]
@gssggssg  已修复

**Comment by nullptr-z** [comment]
修复版本[v4.14.2](https://github.com/uiwjs/uiw/commit/f6e5176796ff2300228c5aaa511a911ab9ed0b7f)
