### ISSUE TITLE
const md = await import('./components/affix/index.md');

### ISSUE THREAD

**Issue by HadeAs** [uiwjs/uiw#69]
why did the above code return a  new path not a compiled content string

**Comment by HadeAs** [comment]
md value is `/static/media/index.32ddf2dd.md`

**Comment by jaywcjlove** [comment]
@HadeAs Add webpack loader.

https://github.com/uiwjs/uiwjs.github.io/blob/c2ddf66e549c27063d33da580531ae3e147b526f/.kktrc.js#L50-L56
