### ISSUE TITLE
[SearchSelect <组件搜索选择器>]:  不能正确禁用

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#692]
### 描述错误

SearchSelect 在设置了 `disabled={true}` 只是在 `input` 框呈现禁用状态，但其实还是可以进行搜索选择，和清除操作

### 错误复现

重现行为的步骤：

1.  进入我提供在线实例
2.  点击禁用的输入框
3.  出现下拉框后，点击某项

### 测试代码

```jsx

const Demo = () => {
  const selectOption = [
    { label: "a1", value: 1 },
    { label: "a2", value: 2 },
    { label: "a3", value: 3 }
  ];
  return (
    <div>
      <SearchSelect
        mode="multiple"
        disabled={true}
        showSearch={true}
        labelInValue={true}
        allowClear
        option={selectOption}
        placeholder="请输入选择"
      />
    </div>
  );
};
```

### 提供在线重现示例
在线实例地址
[![Open in CodeSandbox](https://img.shields.io/badge/Open%20in-CodeSandbox-blue?logo=codesandbox)](https://codesandbox.io/s/uiw-demo-forked-gk9bin)

### 预期行为

当设置禁用后，不出现下拉选择框，也不能进行选择和清除操作

### 截图
设置无效
![image](https://user-images.githubusercontent.com/87160683/159022792-ae49883f-d255-41ed-bf29-0919b8077e34.png)

### 桌面（请填写以下信息）：

- UIW：[4.14.2](https://uiwjs.github.io/#/)
- 操作系统：windows10
- 浏览器：Chrome
- 版本和构建： 99.0.4844.74（正式版本） （64 位）

**Comment by nullptr-z** [comment]
@gssggssg 已修复 发布版本v4.15.0
