### ISSUE TITLE
[select]希望下拉框的长度可以有限制

### ISSUE THREAD

**Issue by didiboji** [uiwjs/uiw#706]
**描述您想要的解决方案**

select的下拉框的长度可以设定为一个值，限制长度，并且可以上下滚动
![image](https://user-images.githubusercontent.com/52915367/159628433-9a66395b-4189-433c-9909-e561c455f356.png)

**Comment by nullptr-z** [comment]
@didiboji 对原生的select下拉项控制样式 有点困难

**Comment by jaywcjlove** [comment]
@didiboji 这个是原生的，超出屏幕是有滚动的，还有一个特点就是能超出浏览器界面之外，这个不是问题。
