### ISSUE TITLE
[SearchSelect <搜索选择器>]: onSearch事件触发不正常

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#737]
### 描述错误

onSearch事件的 不仅仅 在文本框值变化时会进行回调
在移动浏览器控制台位置的时候会进行不正常的触发

### 错误复现

重现行为的步骤：

1. 转到 uiw 的[SearchSelect](https://uiwjs.github.io/#/components/search-select)
2.  打开 __启用搜索__ 的 代码编辑
3. 向 20行代码 `handleSearch` 函数  添加日志打印 `console.log`
5. 可以打开控制台并上下移动控制台位置

### 预期行为

只希望在搜索文本框值变化时进行触发回调

### 截图
当我在xiu'gai修改代码的时候，也会触发
![image](https://user-images.githubusercontent.com/87160683/161361632-223feb59-70d9-49b7-9727-cc8290e4226c.png)

### 桌面（请填写以下信息）：

- UIW：[4.18.0](https://uiwjs.github.io/#/)
- 操作系统：win10
- 浏览器：Chrome
- 版本和构建： 100.0.4896.60（正式版本） （64 位）

**Comment by nullptr-z** [comment]
相关修复
- [ ] https://github.com/uiwjs/uiw/pull/738
