### ISSUE TITLE
侧边栏弹出提示框问题

### ISSUE THREAD

**Issue by hy916** [uiwjs/uiw#74]
鼠标放到侧边栏这里时，有个弹出提示框，然后滑动鼠标上下移动，结果这个提示框也下去了。
![image](https://user-images.githubusercontent.com/32630937/65844494-1848b480-e369-11e9-8889-ffa2113b5d9d.png)

**Comment by jaywcjlove** [comment]
@huyi0916 了解。

**Comment by jaywcjlove** [comment]
@huyi0916 调试原因是左边一级导航菜单 `position: fixed;`

**Comment by huyi0916** [comment]
恩恩好的 ，我在工作中也遇到过这样的问题，没有解决，我也试试是不是你这个方法。
