### ISSUE TITLE
【Select】select在表单提交中，value值始终取string类型

### ISSUE THREAD

**Issue by dibenny** [uiwjs/uiw#742]
如图：
![image](https://user-images.githubusercontent.com/44771226/161371564-916c123a-b5fc-461b-85a3-25d8e452d39d.png)

期望：
选中数据后，提交表单值时可根据设置的value值类型取值提交

**Comment by nullptr-z** [comment]
@dibenny 有问题请按[模板](https://github.com/uiwjs/uiw/issues/new/choose)书写
