### ISSUE TITLE
[Tree<树形控件>]: checkStrictly不起作用

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#756]
### 描述错误

Tree]: checkStrictly不起作用

### 错误复现
设置了checkStrictly为false不生效

### 预期行为

能够正确的使用

### 截图

![image](https://user-images.githubusercontent.com/87160683/162679534-cead9c84-07c3-4547-92ef-faf0215a034e.png)

### 桌面（请填写以下信息）：

- UIW：[例如 v[4.20.0](https://uiwjs.github.io/#/)]
- 操作系统：win10
- 浏览器：Chrome
- 版本和构建：版本 100.0.4896.75（正式版本） （64 位）

**Comment by nullptr-z** [comment]
@gssggssg 测试后是正常工作的，这个属性的作用是勾选父级的时候是否勾选子节点； 勾选子节点一定会勾选父节点，与这个属性无关
