### ISSUE TITLE
能否大致说一下打包原理

### ISSUE THREAD

**Issue by souoxs** [uiwjs/uiw#76]
Hi 你好 

我们也在做react + typescript组件封装

抛开你的kkt

可否大致讲一下打包原理以及如何打包支持react ssr

**Comment by jaywcjlove** [comment]
@souoxs React SSR 在这里有说一点，至于打包原理满大街都是教程，自己搜一搜吧。
https://github.com/jaywcjlove/handbook/issues/27

**Comment by souoxs** [comment]
我的意思是webpack打包这一层 我们现在tsx打包出来 react ssr会报错

方便的话 加微信：xiaopohaidigua

希望答疑解惑 不胜感激

**Comment by jaywcjlove** [comment]
@souoxs 看代码，临摹代码，是最好的学习方式。[kktjs/kkt-ssr](https://github.com/kktjs/kkt-ssr)
