### ISSUE TITLE
[SearchSelect <搜索选择器>]: 没有初始值时不能正确重置

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#760]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

在表单中使用时，SearchSelect 没有设置初始值的情况下，重置是没有效果的

### 错误复现

重现行为的步骤：

1. 转到“[SearchSelect 搜索选择器](https://uiwjs.github.io/#/components/search-select)”
2. 向下滚动到“在表单中使用 ”栏目，给表单增加重置按钮
3. 取消SearchSelect 的初始值
4. 点击重置

### 预期行为

当SearchSelect 没有设置初始值时，重置表单后，应该将SearchSelect 的搜索框清空

### 截图

![35736dc148f27a9661ca8c372ab1f26](https://user-images.githubusercontent.com/87160683/162721063-60a9e5d9-e6a8-43de-9246-61c363891f57.png)

### 桌面（请填写以下信息）：

- UIW：[4.20.0](https://uiwjs.github.io/#/)
- 操作系统：windows10
- 浏览器：Chrome
- 版本和构建：100.0.4896.75（正式版本） （64 位）

**Comment by nullptr-z** [comment]
@gssggssg 已修复问题，预计4.20.1中发布
