### ISSUE TITLE
[Menu <菜单>]: 二级下拉菜单不生效

### ISSUE THREAD

**Issue by gssggssg** [uiwjs/uiw#769]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

二级菜单不可下拉
![3563b2f53bbba0291c563da4911ed41](https://user-images.githubusercontent.com/87160683/163511197-b9032c8e-e7ac-4f46-9766-9c568373193e.png)
这菜单里面有内容，高度还是1，下拉菜单无效

### 错误复现

重现行为的步骤：

1. 转到 [uiw Menu 菜单](https://uiwjs.github.io/#/components/menu)
2. 向下滚动到“基本用法”
3. 点击可下拉的 __月统计报表导出__

### 预期行为

能够正确展示下拉菜单

### 截图

点击可下拉的 __月统计报表导出__
![image](https://user-images.githubusercontent.com/87160683/163511057-e615b866-3d68-4ae5-aff1-abb3671ce52b.png)

### 桌面（请填写以下信息）：

- UIW：[[4.21.0](https://uiwjs.github.io/#/)]
- 操作系统：[windows10]
- 浏览器：[Chrome]
- 版本和构建：[100.0.4896.88（正式版本） （64 位）]

**Comment by nullptr-z** [comment]
@gssggssg 已修复
