### ISSUE TITLE
[Tooltip <文字提示>]: Button组件禁用的时候会偶尔性的出现提示框

### ISSUE THREAD

**Issue by dibenny** [uiwjs/uiw#772]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

使用Tooltip包裹button组件时，给button添加disabled属性会偶尔性的出现提示弹窗

### 提供在线重现示例
![image](https://user-images.githubusercontent.com/44771226/163537433-6db4e843-d10c-4aa3-96f1-deda9c8506d7.png)

### 期望
不要出现弹窗提示

### 桌面（请填写以下信息）：

- UIW：[例如 v4.21.0]
- 操作系统：[例如 macOS]
- 浏览器：[Chrome]

**Comment by nullptr-z** [comment]
@dibenny 已修复
