### ISSUE TITLE
[searchSelect]: 表单中使用searchSelect并加上disabled属性就会出现样式问题

### ISSUE THREAD

**Issue by dibenny** [uiwjs/uiw#798]
注意：根据下面内容复现错误问题，以方便测试。

### 描述错误

表单中使用searchSelect并加上disabled属性就会出现样式问题

### 错误复现
![image](https://user-images.githubusercontent.com/44771226/165668119-2c4ee2bd-91dd-4366-89a8-df253adfc839.png)

### 预期行为

置灰范围包括整个选择框，无两边空余留白

### 桌面（请填写以下信息）：

- UIW：[ v4.21.3]
- 操作系统：[macOS]
- 浏览器：[Chrome]
- 版本和构建：[59.0.2（64 位）]

**Comment by cuilanxin** [comment]
@dibenny 
已解决
* https://github.com/uiwjs/uiw/pull/801
