### ISSUE TITLE
我在使用您Form组件遇到一个问题,希望能得到解决!

### ISSUE THREAD

**Issue by ptr-zero** [uiwjs/uiw#80]
当我进行提交数据,但是服务端返回错误,如在再一次请求还是返回错误,这时Form表单就会被重置

**Comment by jaywcjlove** [comment]
@ptr-zero  可以根据这个实例准确描述一下问题。没有明白。

**Comment by jaywcjlove** [comment]
https://codepen.io/jaywcjlove/pen/KKKOwJY?&editable=true&editors=0010

**Comment by ptr-zero** [comment]
![image](https://user-images.githubusercontent.com/48251883/69770861-925cb480-11c5-11ea-8064-dd2a9fbda288.png)
我在Form表单中的填写数据只要通过了表单验证,表单就会被清空;
数据被提交到服务端,返回错误(417),当我想重新填写表单时,发现表单已经被置空了

**Comment by jaywcjlove** [comment]
@ptr-zero 更新 `+ uiw@3.10.0` 测试一下看看
