### ISSUE TITLE
create-react-app引入报错

### ISSUE THREAD

**Issue by sodatodo** [uiwjs/uiw#97]
使用环境 windows10 && macOS 10.15.4
uiw版本 3.10.10
使用create-react-app --template typescript 创建的项目在引入uiw后会出现TypeScript error in /node_modules/uiw/lib/cjs/index.d.ts
已经将node_module写入tsconfig的exclude中，且在3.10.9版本中无此bug

**Comment by sodatodo** [comment]
貌似是 export type { SplitProps, SplitState } from '@uiw/react-split';造成的,我对ts的理解还不够深入，如果有我的配置问题还请指教

**Comment by jaywcjlove** [comment]
@sodatodo 可以将实例上传我看一哈。

**Comment by sodatodo** [comment]
https://github.com/sodatodo/error-demo

**Comment by sodatodo** [comment]
不太会用线上的那种重现工具，就图一方便临时建了一个

**Comment by jaywcjlove** [comment]
@sodatodo 确实是类型错误，更新 `uiw@3.10.11`

**Comment by jaywcjlove** [comment]
@sodatodo thx!
