### ISSUE TITLE
[Tooltip] Tooltip appearing below Heatmap (prod only)

### ISSUE THREAD

**Issue by mmurph24** [uiwjs/uiw#971]
When I user react-heatmap and react-tooltip locally, everything is working as expected:

![image](https://github.com/uiwjs/uiw/assets/18620218/ff518295-e0e1-4753-9f5e-40505d917f84)

When I deploy to production (Rails app on Fly.io), the tooltip appears in the wrong place:

![image](https://github.com/uiwjs/uiw/assets/18620218/66227a1f-4788-43b8-8f18-9c9d12218a9a)

Adding `@import '@uiw/react-tooltip/dist.css';` to `application.scss` changed the issue from unstyled text to the styled tooltip, but I'm not sure what else I need to do to get this placement working.

Thanks!

**Comment by mmurph24** [comment]
Disregard, I was able to figure this out! I needed to import a bunch of additional css as well (heat-map, overlay, overlay-trigger) to get it all working.

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/sweet-aj-jpl6mx?fontsize=14&hidenavigation=1&theme=dark

```jsx
import Tooltip from "@uiw/react-tooltip";
import HeatMap from "@uiw/react-heat-map";

const value = [
  { date: "2016/01/11", count: 2 },
  ...[...Array(17)].map((_, idx) => ({
    date: `2016/01/${idx + 10}`,
    count: idx
  })),
  ...[...Array(17)].map((_, idx) => ({
    date: `2016/02/${idx + 10}`,
    count: idx
  })),
  { date: "2016/04/12", count: 2 },
  { date: "2016/05/01", count: 5 },
  { date: "2016/05/02", count: 5 },
  { date: "2016/05/03", count: 1 },
  { date: "2016/05/04", count: 11 },
  { date: "2016/05/08", count: 32 }
];

export default function App() {
  return (
    <div>
      <HeatMap
        value={value}
        width={600}
        startDate={new Date("2016/01/01")}
        rectRender={(props, data) => {
          console.log("props", props);
          // if (!data.count) return <rect {...props} />;
          return (
            <Tooltip placement="top" content={`count: ${data.count || 0}`}>
              <rect {...props} />
            </Tooltip>
          );
        }}
      />
    </div>
  );
}
```

@mmurph24  I found that StrictMode triggers this error.

```
import { StrictMode } from "react";
```
