### ISSUE TITLE
数据在更新之后列表高度没有刷新

### ISSUE THREAD

**Issue by 58bcbedf47bd91439c** [uiwjs/uiw#974]
https://github.com/uiwjs/uiw/assets/25519902/bc1fdfa6-cd2e-4d82-931d-7f3622466b52

**Comment by jaywcjlove** [comment]
@58bcbedf47bd91439c 这是使用的 `Collapse 折叠面板` 组件？可以提供可以重现错误的示例，我看一下

**Comment by 58bcbedf47bd91439c** [comment]
> @58bcbedf47bd91439c 这是使用的 `Collapse 折叠面板` 组件？可以提供可以重现错误的示例，我看一下

import { useState } from "react";
import "./styles.css";
import Collapse from "@uiw/react-collapse";
export default function App() {
  const [recent, setRecent] = useState([]);
  const [list, setList] = useState(["a", "b", "c", "d", "e"]);
  const onListClick = (index) => {
    const newList = [...list];
    const ls = newList.splice(index, 1);
    setRecent([...recent, ls]);
    setList(newList);
  };
  const onRecentClick = (index) => {
    const newRecent = [...recent];
    const ls = newRecent.splice(index, 1);
    setList([...list, ls]);
    setRecent(newRecent);
  };
  return (
    <div className="App">
      <Collapse>
        <Collapse.Panel header="Test1">
          {recent.map((item) => {
            return (
              <div className="item" key={item} onClick={onRecentClick}>
                {item}
              </div>
            );
          })}
        </Collapse.Panel>
        <Collapse.Panel header="Tset2">
          {list.map((item) => {
            return (
              <div className="item" key={item} onClick={onListClick}>
                {item}
              </div>
            );
          })}
        </Collapse.Panel>
      </Collapse>
    </div>
  );
}

**Comment by 58bcbedf47bd91439c** [comment]
> @58bcbedf47bd91439c 这是使用的 `Collapse 折叠面板` 组件？可以提供可以重现错误的示例，我看一下
https://codesandbox.io/s/fast-fog-lh8dlx?file=/src/styles.css

**Comment by jaywcjlove** [comment]
@58bcbedf47bd91439c 升级到 `v4.22.1`，这个因为高度动画引起的，现在计算了子节点的高度，这样可能存在隐患，比如子节点 通过 position 定位就会发生计算错误

**Comment by 58bcbedf47bd91439c** [comment]
> @58bcbedf47bd91439c 升级到 `v4.22.1`，这个因为高度动画引起的，现在计算了子节点的高度，这样可能存在隐患，比如子节点 通过 position 定位就会发生计算错误


https://github.com/uiwjs/uiw/assets/25519902/cc37d1aa-591d-47db-9568-e5c0086ae735

https://codesandbox.io/s/fast-fog-lh8dlx?file=/src/App.js
我更新了新的版本，项目中高度会根据类型增加额外的，但是在示例中是正常，我再调试看看

**Comment by 58bcbedf47bd91439c** [comment]
> @58bcbedf47bd91439c 升级到 `v4.22.1`，这个因为高度动画引起的，现在计算了子节点的高度，这样可能存在隐患，比如子节点 通过 position 定位就会发生计算错误

你好，我找到原因了， offsetHeight  包括元素的边框、内边距和滚动条（如果存在）的高度，代码中额外增加了，padingTop 很热paddingBottom 
![image](https://github.com/uiwjs/uiw/assets/25519902/3b62df15-8053-496a-84ce-759270d9e5ff)

**Comment by jaywcjlove** [comment]
@58bcbedf47bd91439c 不需要这个高度？

**Comment by 58bcbedf47bd91439c** [comment]
> @58bcbedf47bd91439c 不需要这个高度？

高度计算重复了

**Comment by jaywcjlove** [comment]
@58bcbedf47bd91439c https://codesandbox.io/embed/quizzical-curran-jh78pg?fontsize=14&hidenavigation=1&theme=dark

上面是不需要更新即可解决问题


```jsx
<Collapse.Panel header="Test1">
  <div>
  </div>
</Collapse.Panel>
```

在 `Panel` 里面套一层 div

**Comment by 58bcbedf47bd91439c** [comment]
> @58bcbedf47bd91439c https://codesandbox.io/embed/quizzical-curran-jh78pg?fontsize=14&hidenavigation=1&theme=dark
> 
> 上面是不需要更新即可解决问题
> 
> ```js
> <Collapse.Panel header="Test1">
>   <div>
>   </div>
> </Collapse.Panel>
> ```
> 
> 在 `Panel` 里面套一层 div
测试可以，感谢支持！
